### PR TITLE
Updated brcmfmac 4356 (AP6356S used in NanoPi M4/M4V2 and NanoPC T4)

### PR DESCRIPTION
**Pull request by piter75**
Closes: [AR-340]

This should fix WiFi networking for AP6356S based boards.
Firmware source: [Cypress Linux WiFi Driver Release (FMAC) [2020-04-02]](https://community.cypress.com/docs/DOC-19375)

```
[  303.853762] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4356-sdio for chip BCM4356/2
[  303.866305] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4356/2 wl0: Mar  4 2020 22:06:08 version 7.35.349.87 (r724447 CY) FWID 01-c68a2890
```

Copied current brcmfmac4356-sdio.{bin,txt} to brcmfmac43456-sdio.{bin,txt} respectively to not break 43456 - they were linked until now.
Tested for connectivity using both NanoPi M4 and M4V2 - the latter run 48 hours connected to 5GHz AP without issues with a few iperf3 tests performed during that time (200-280mbps).

@martinayotte I see you were the last to modify brcmfmac4356-sdio.{bin,txt} for OrangePi 3 but I suppose you actually wanted to modify brcmfmac43456-sdio.{bin,txt} that were linked to it. The latter are used for AP6256 found in OrangePi 3
Can you test if it still works well with OrangePi 3 after the update?

[AR-340]: https://armbian.atlassian.net/browse/AR-340

### CODE REVIEW

**Comment by martinayotte** [comment]
@piter75 , unfortunately, using this newer version on my OPi3 doesn’t work, no wlan0 appears, and dmesg reveal the following : 
`
[    9.621255] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
[   10.629457] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
`
I had to revert to previous version ...

**Comment by igorpecovnik** [comment]
I guess we will need to work this https://github.com/armbian/build/issues/1837 out as soon as possible.

**Comment by piter75** [comment]
> unfortunately, using this newer version on my OPi3 doesn’t work

@martinayotte thanks for testing
can you share the results of `dmesg | grep brcmfmac`?

my change can be replicated with the running system in the following way:
```
cd /lib/firmware/brcm
rm brcmfmac43456-sdio.*
mv brcmfmac4356-sdio.bin brcmfmac43456-sdio.bin
mv brcmfmac4356-sdio.txt brcmfmac43456-sdio.txt
wget https://github.com/armbian/firmware/raw/brcmfmac-4356-update-firmware/brcm/brcmfmac4356-sdio.bin
wget https://github.com/armbian/firmware/raw/brcmfmac-4356-update-firmware/brcm/brcmfmac4356-sdio.clm_blob
wget https://github.com/armbian/firmware/raw/brcmfmac-4356-update-firmware/brcm/brcmfmac4356-sdio.txt
reboot
```
Could you test it with this procedure in the running system?

lines 2-5 are for preserving AP6256 firmware - removing links to (IMHO) wrongly named files and replacing them with its contents
lines 6-8 are for updating the AP6356S one

I tested it with OrangePi 4 (which also uses AP6256) and it works fine but maybe OrangePi 3 module has some different chip revision inside.
My output (after the change):
```
[    3.891473] brcmfmac: F1 signature read @0x18000000=0x15294345
[    3.897121] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43456-sdio for chip BCM4345/9
[    3.899852] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac43456-sdio.xunlong,orangepi-4.txt failed with error -2
[    4.000656] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43456-sdio for chip BCM4345/9
[    4.000705] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[    4.001193] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/9 wl0: Jun 16 2017 12:38:26 version 7.45.96.2 (66c4e21@sh-git) (r) FWID 01-1813af84
```

**Comment by piter75** [comment]
> I guess we will need to work this [armbian/build#1837](https://github.com/armbian/build/issues/1837) out as soon as possible.

Yeah... if Martin's retest with provided steps will not work then I see no other way to have both NanoPi M4/T4 and OrangePi 3 working now :(

**Comment by martinayotte** [comment]
@piter75 , oh ! I didn't removed the symbolic links, I've only put old version aside and wget the new one.
So, your steps means that OPi3 will still use old one since you've done "mv brcmfmac4356-sdio.bin brcmfmac43456-sdio.bin" ...
Then, I've retested using your exact same steps, and it still working :-) 

[    8.587874] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43456-sdio for chip BCM4345/9
[    8.601984] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac43456-sdio.xunlong,orangepi-3.txt failed with error -2
[   10.701363] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43456-sdio for chip BCM4345/9
[   10.701480] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[   10.701927] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/9 wl0: Jun 16 2017 12:38:26 version 7.45.96.2 (66c4e21@sh-git) (r) FWID 01-1813af84

**Comment by piter75** [comment]
> I didn't removed the symbolic links, I've only put old version aside and wget the new one

I suspected that ;-) That's why I prepared the replication steps to make it clear what is being done.

> I've tested that on NanoPiM4V2 and OrangePi-RK3399 and RockPi-4B as well ...

Great! Thanks again for testing!

@lanefu we are a bit late in the release cycle but with firmwares which are picked up by stable point releases from master it's probably never a safe time.
I propose to merge it in and if it backfires during RCs then we can always revert.

**Comment by lanefu** [comment]
> @lanefu we are a bit late in the release cycle but with firmwares which are picked up by stable point releases from master it's probably never a safe time.
> I propose to merge it in and if it backfires during RCs then we can always revert.

Makes sense to me.

**Comment by zhangn1985** [comment]
hi, all

don't struggle here, please help to finish the idea: build firmware packages for each devices, which I shown in online meeting..

https://github.com/armbian/build/commit/2b2d368ffe1c6f3ec5f381caf111de7cffe981f4 here is the example.

**Comment by zhangn1985** [comment]
https://github.com/armbian/build/commit/1c9d3834d6be1b06e865d8056f862e002d697b9f

**Comment by piter75** [comment]
> don't struggle here, please help to finish the idea: build firmware packages for each devices, which I shown in online meeting

As much as I like the idea of split firmware packages per device... issues this PR deals with are orthogonal to the idea (IMHO).
No matter what mechanism we use we still need to update firmware files from time to time and resolve simple firmware misplacement issues ;-)

**Pull request merged**
