### PR TITLE
XR819: Update firmware

### PR DESCRIPTION
**Pull request by EvilOlaf**
Adopted from https://github.com/karabek/xradio/pull/1

Needs testing!

### CODE REVIEW

**Comment by EvilOlaf** [comment]
What I did for testing so far:

simply download and overwrite the current firmware file and reboot ✅

```
root@orangepizero:~# dmesg|grep firmware
[   10.754304] xradio: firmware vers. 8 (WSM), build 5258, api 1060, cap 0x0003
```
looking good ✅

```
root@orangepizero:~# iwlist wlan0 scan|grep ESS
                    ESSID:"Martin Router King"
```
looking good ✅

**Comment by igorpecovnik** [comment]
Nothing much to loose in any case, right?

**Comment by EvilOlaf** [comment]
Your guess is as good as mine...

**Comment by igorpecovnik** [comment]
OK, lets wait a few days - if we got some more folks on testings - then merge.

**Comment by EvilOlaf** [comment]
Seems fine
https://forum.armbian.com/topic/16171-test-new-xradio-firmware/?do=getLastComment

**Comment by EvilOlaf** [comment]
Neither improvements nor regressions from feedback collected. I'd say merge and if complains increase revert.

**Pull request merged**
