### PR TITLE
Update AP6256 firmware

### PR DESCRIPTION
**Pull request by tianyuanhao**
[These](https://github.com/MYiR-Dev/meta-myir-imx/tree/develop/meta-bsp/recipes-myir/ap6256/ap6256/lib/firmware/bcmd) are the newest firmware available on the Internet for AP6256.

I tested them running Linux 5.8.3 on ROCK Pi 4 for more than 12 hours.

### CODE REVIEW

**Comment by tianyuanhao** [comment]
43200 packets transmitted, 43021 packets received, 0% packet loss
round-trip min/avg/max = 2.477/21.971/2246.158 ms

**Comment by piter75** [comment]
@tianyuanhao does this update solve any particular issue you have encountered with the current firmware?

I must admit that I am a bit reluctant to taking it on the grounds that we actually do not know its origin - beside the fact that it was found in some repo on Github.

I know most of the blobs in this repo have the similar (some even lower) level of traceability but with AP6256 it is a bit different story.
Current version is the one that [Radxa received from Ampak](https://github.com/armbian/build/issues/1812#issuecomment-592270124) in response to Kr00k and [contributed to the firmware repo](https://github.com/armbian/firmware/pull/12).

@igorpecovnik WDYT?

**Comment by tianyuanhao** [comment]
@piter75 In fact they do not solve any problems, except for the higher version number.

Radxa only provides a newer binary firmware, but the text configuration is still in a very old version, even older than the version in rockchip-linux/rkwifibt (which no longer exists).

As far as I know, both MYiR and Radxa are Chinese manufacturers. The firmware provided by MYiR should be as trustworthy as Radxa.

By the way, currently, the AP6256 firmware widely adopted by the community is located at https://gitlab.manjaro.org/manjaro-arm/packages/community/ap6256-firmware.

**Comment by piter75** [comment]
> but the text configuration is still in a very old version, even older than the version in rockchip-linux/rkwifibt (which no longer exists)

That's true. I just found out that rockchip's repo is gone while trying to find if they had updated their version recently.
I hope you are aware that the values provided in the nvram file are actually device specific. ;-)

> the AP6256 firmware widely adopted by the community is located at

The wifi blob is exactly the same as Armbian's but it has both newer bluetooth and nvram files.

I would opt for keeping the wifi blob as it is now and update both bluetooth and nvram files as they are both pretty outdated and of doubtful origin. WDYT?

**Comment by igorpecovnik** [comment]
> keeping the wifi blob as it is now and update both bluetooth and nvram 

OK for me.

**Comment by tianyuanhao** [comment]
> I hope you are aware that the values provided in the nvram file are actually device specific.

For brcmfmac43456, the nvram file is device-specific. However, for AP6256, the nvram file should be the same.

> The wifi blob is exactly the same as Armbian's

Yes, I requested the maintainer to use Armbian's AP6256 binary firmware. But now, MYiR's AP6256 binary firmware is newer.

Radxa: *Version: 7.45.96.61 (be7af2d@shgit) (r745790) CRC: 279731d4 Date: Tue 2020-02-11*
MYiR: *Version: 7.45.96.68 (f9ee141@shgit) (r745790) CRC: 4c5b2580 Date: Mon 2020-07-06*

> I would opt for keeping the wifi blob as it is now and update both bluetooth and nvram files as they are both pretty outdated and of doubtful origin.

I think we can be more aggressive and use all the AP6256 firmware from MYiR. They were updated together recently.

**Comment by lanefu** [comment]
@piter75 do you think this is safe to merge..... I was going to add this firmware for pine book pro, but this looks like an even newer version than what manjaro is using

https://gitlab.manjaro.org/manjaro-arm/packages/community/ap6256-firmware

**Comment by piter75** [comment]
> do you think this is safe to merge..... I was going to add this firmware for pine book pro, but this looks like an even newer version than what manjaro is using

I am simply a bit concerned about the lack of full traceability of the wifi blob origin file especially in comparison to the version we already have.
On the other hand we have tons of blobs with unknown origins in armbian/firmware so one or two files do not really make a big difference.

**Comment by lanefu** [comment]
Okay I did some basic iperf3 testing with our original Armbian firmware.. the firmware used by manjaro, and the firmware used by myir...

the manjaro and the myir firmware both fix bluetooth on the Pinebook pro....

..but I did consistently get some retransmits with both manjaro and myir firmwares.. but not the original....

see tests here:  I did a iperf forward and reverse test for each firmware.

http://ix.io/2xH3

**Comment by lanefu** [comment]
had a friend try with nicer wifi...

before.. had a few retransmits.. rate 144/146

after

45/43 with 198 retransmits..

wifi throughput halved.... but bluetooth works 🤦

**Comment by lanefu** [comment]
@tianyuanhao did you do any iperf3 throughput testing before and after on your rock pi 4?

**Comment by tianyuanhao** [comment]
@lanefu I might try it this weekend.

**Comment by tianyuanhao** [comment]
@lanefu ROCK Pi 4 Linux 5.9-rc5 [patched](https://patchwork.kernel.org/patch/11711809/)

**Armbian** firmware:

```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-20.00  sec  64.1 MBytes  26.9 Mbits/sec    0             sender
[  5]   0.00-20.78  sec  63.8 MBytes  25.8 Mbits/sec                  receiver
```

```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-20.03  sec   101 MBytes  42.4 Mbits/sec   37             sender
[  5]   0.00-20.00  sec   101 MBytes  42.2 Mbits/sec                  receiver
```

**Manjaro** firmware:

```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-20.00  sec  54.5 MBytes  22.8 Mbits/sec    3             sender
[  5]   0.00-20.47  sec  54.5 MBytes  22.3 Mbits/sec                  receiver
```

```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-20.02  sec  94.1 MBytes  39.4 Mbits/sec   35             sender
[  5]   0.00-20.00  sec  93.5 MBytes  39.2 Mbits/sec                  receiver
```

**MYiR** firmware:

```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-20.00  sec   109 MBytes  45.9 Mbits/sec   11             sender
[  5]   0.00-20.03  sec   107 MBytes  44.8 Mbits/sec                  receiver
```

```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-20.01  sec   107 MBytes  45.0 Mbits/sec   18             sender
[  5]   0.00-20.00  sec   107 MBytes  44.8 Mbits/sec                  receiver
```

**Comment by lanefu** [comment]
since no regression for rockpi4.. going to go ahead and merge... PBP tuning will be workin progress.. if we have to roll back we'll roll back.

**Comment by lanefu** [comment]
Going to roll this back and only cherry-pick in `BCM4345C5.hcd`

I had really bad re-transmits and packetloss with PBP....   best performance was with our orignal firmware and only this bluetooth firmware.

**Pull request merged**
